package(default_visibility = ["//visibility:public"])

java_library(
    name = "dripcoffee",
    srcs = glob(["*.java"]),
    deps = [
        "//java/coffee:interfaces",
        "//third_party:dagger",
    ],
)
